### ISSUE TITLE
Edit/delete multiple items?

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#553] opened 2016-03-11 19:48 UTC
Is there a plan to make it possible for (super/global) to edit multiple items at once? There are two specific instances I could currently use:
- mass add items to an item set
- delete more than one item at a time (a group of 5-10)

**Comment by zerocrates** [comment] 2016-08-29 18:36
Duplicate of #326

**Closed by zerocrates** 2016-08-29 18:36 UTC
Labels: question
