### ISSUE TITLE
A note and some problems for displaying items informations on backoffice

### ISSUE THREAD

**Issue by jeau** [omeka/omeka-s#610] opened 2016-04-21 10:40 UTC
On item show view, is there any reason to align metadata on right ?
This layout makes it difficult to read and is not consistent with other views

There are also other problems (I use OSX with Firefox and Chrome): 

- If there is a linked resource, alignment is left but the sidebar hides the information (Predicate 	Object). 
- If there is no linked resource, the message is centered but is also covered by the sidebar
- so, after selecting the Linked Resource tab, when I return to the Metadata tab, the titles of the metadata fields disappear (in fact behind sidebar ;)

![capture d ecran 2016-04-21 a 12 24 49](https://cloud.githubusercontent.com/assets/3129299/14706198/8c6ba2f4-07bd-11e6-8719-30acf5a97e2b.png)
![capture d ecran 2016-04-21 a 12 25 09](https://cloud.githubusercontent.com/assets/3129299/14706203/94f9e868-07bd-11e6-9d35-df329ac65cd6.png)
![capture d ecran 2016-04-21 a 12 25 19](https://cloud.githubusercontent.com/assets/3129299/14706209/9d03addc-07bd-11e6-8229-fab4934a5f3b.png)

**Comment by zerocrates** [comment] 2016-04-21 13:27
Not sure what's going on with those metadata headings: they're supposed to be aligned left.

The sidebar stuff is almost certainly a regression from a change we just made to the handling of sidebars within tabs.

**Comment by zerocrates** [comment] 2016-04-21 14:25
@kimisgold the second two points here are a regression caused by #607 (both tabs on the show page here are perfect examples of the kind that script doesn't deal with correctly: the tabs each don't have a sidebar, but the _page_ does, it's just outside the tabs)

**Comment by zerocrates** [comment] 2016-04-21 17:24
I can't reproduce the other part of this issue, where the property headings are aligning right. The stylesheet sets those to align left specifically, and they're supposed to fit into the gap to the left of the values.

**Comment by jeau** [comment] 2016-04-21 19:34
on top, the div of each metadata (property heading and value) is set to align right, 

cf https://github.com/omeka/omeka-s/blob/develop/application/asset/css/style.css#L2532
and the following lines

in this context, the property heading is set to align left but inside a block whose width is 22.22% (77.77 for the value)

**Comment by zerocrates** [comment] 2016-04-21 19:43
Yeah, the right/left alignment is there to get additional values to stack up underneath each other aligned with the edge of the property label. We may replace this with a version that doesn't mess with the alignment, but I can't find anywhere except for your report where the alignment does what's in your screenshots. For reference, this is what it normally looks like:

![image](https://cloud.githubusercontent.com/assets/298975/14722074/c2ab4a12-07d7-11e6-8253-bc0d133799f5.png)

Are you pulled up to current on develop?

**Comment by jeau** [comment] 2016-04-21 22:12
Yes, I m ok with your reference for displaying item informations.
My installation was up to date on git development.

I just do a full reinstall from Github, but the result is the same.
I can give you an account on my dev omeka-s instance http://emf.tech

**Comment by jeau** [comment] 2016-04-22 20:25
It's corrected. This recent commit solves the problem of aligment on my installation.
https://github.com/omeka/omeka-s/commit/1a5279c26dee06c9b51033d8c2a4f5081c66d29e

**Comment by zerocrates** [comment] 2016-04-22 20:26
And just for confirmation, is the other problem, where things were being hidden behind the sidebar, also fixed? It should have been fixed by a commit from earlier today.

**Comment by jeau** [comment] 2016-04-22 21:43
Indeed. I do not see any problems.

**Comment by zerocrates** [comment] 2016-04-23 01:15
Thanks for the report and the confirmation.

**Closed by zerocrates** 2016-04-23 01:15 UTC
Labels: bug
