### ISSUE TITLE
Site-level results per page setting

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1278] opened 2018-06-22 19:45 UTC
In addition to the Global setting "results per page," have a results per page setting in Site Settings, so that sites using a grid browse can set things at an optimal number (multiple of 4), while maintaining a useful number of items per page on the admin side. 

We already do this in Classic to make the admin side easier to manage, and it would be a useful site-level setting given the variance in theme item browse display.

**Comment by zerocrates** [comment] 2018-06-22 19:46
Duplicate of #1272

**Closed by zerocrates** 2018-06-22 19:46 UTC
