### ISSUE TITLE
Restrict item set in advanced search

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1723] opened 2021-06-04 10:13 UTC
This is a feature request to list only item sets attached to the relevant site in the advanced search form.

Also on this matter: the open pull request https://github.com/omeka/omeka-s/pull/1423

**Comment by zerocrates** [comment] 2021-06-07 14:47
This duplicates #1459, so I'm closing it for that reason, but note that the issue is already assigned as current work.

The "used" PR doesn't really do the same thing but I see how it's related in the larger scope of "clearing away irrelevant choices."

**Closed** 2021-06-07 14:48 UTC
