### ISSUE TITLE
Testing: Full-text search for items and site pages

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1417] opened 2019-05-21 17:21 UTC
The [fulltext branch](https://github.com/omeka/omeka-s/compare/fulltext) introduces full-text search for items and site pages. First you'll need to index the full-text by checking the "Index full-text search" checkbox in global settings. When it's done indexing (check the most recent job to confirm) there are several new features you can test:

- The simple search input (admin and public) should return results based on a full-text search. The advanced search should return results for the resource you've selected (item, item set, media). The public search should return results for items _and_ site pages simultaneously, with links to all the results for each.
- The advanced search (admin and public ) includes a "Search full-text" input that should return results based on a full-text search in addition to any other filters you've added.

Note that full-text searches are automatically sorted by relevance, most relevant first, but we are not exposing relevance scores.

**Comment by mebrett** [comment] 2019-05-21 17:54
I checked out the fulltext branch and was prompted to update the database when I went to my install's `/admin`. However, updating returned the following error:

```
Doctrine\DBAL\Exception\DriverException
An exception occurred while executing 'CREATE TABLE fulltext_search (id INT NOT NULL, resource VARCHAR(255) NOT NULL, title LONGTEXT DEFAULT NULL, text LONGTEXT DEFAULT NULL, FULLTEXT INDEX IDX_AA31FE4A2B36786B3B8BA7C7 (title, text), PRIMARY KEY(id, resource)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;': SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes

Details:

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes' in /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('CREATE TABLE fu...')
#1 /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1044): Doctrine\DBAL\Driver\PDOConnection->exec('CREATE TABLE fu...')
#2 /websites/omekadev/home/www/mebrett/testomekas/application/data/migrations/20190514061351_AddFulltextSearch.php(11): Doctrine\DBAL\Connection->exec('CREATE TABLE fu...')
#3 /websites/omekadev/home/www/mebrett/testomekas/application/src/Db/Migration/Manager.php(80): Omeka\Db\Migrations\AddFulltextSearch->up(Object(Doctrine\DBAL\Connection))
#4 /websites/omekadev/home/www/mebrett/testomekas/application/src/Controller/MigrateController.php(31): Omeka\Db\Migration\Manager->upgrade()
#5 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\MigrateController->indexAction()
#6 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#14 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes' in /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59
Stack trace:
#0 /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1044): Doctrine\DBAL\Driver\PDOConnection->exec('CREATE TABLE fu...')
#1 /websites/omekadev/home/www/mebrett/testomekas/application/data/migrations/20190514061351_AddFulltextSearch.php(11): Doctrine\DBAL\Connection->exec('CREATE TABLE fu...')
#2 /websites/omekadev/home/www/mebrett/testomekas/application/src/Db/Migration/Manager.php(80): Omeka\Db\Migrations\AddFulltextSearch->up(Object(Doctrine\DBAL\Connection))
#3 /websites/omekadev/home/www/mebrett/testomekas/application/src/Controller/MigrateController.php(31): Omeka\Db\Migration\Manager->upgrade()
#4 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\MigrateController->indexAction()
#5 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /websites/omekadev/home/www/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#13 {main}

Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'CREATE TABLE fulltext_search (id INT NOT NULL, resource VARCHAR(255) NOT NULL, title LONGTEXT DEFAULT NULL, text LONGTEXT DEFAULT NULL, FULLTEXT INDEX IDX_AA31FE4A2B36786B3B8BA7C7 (title, text), PRIMARY KEY(id, resource)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;':

SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes' in /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /websites/omekadev/home/www/mebrett/testomekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1046): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'CREATE TABLE fu...')
#2 /websites/omekadev/home/www/mebrett/testomekas/application/data/migrations/20190514061351_AddFulltextSearch.php(11): Doctrine\DBAL\Connection->exec('CREATE TABLE fu...')
#3 /websites/omekadev/home/www/mebrett/testomekas/application/src/Db/Migration/Manager.php(80): Omeka\Db\Migrations\AddFulltextSearch->up(Object(Doctrine\DBAL\Connection))
#4 /websites/omekadev/home/www/mebrett/testomekas/application/src/Controller/MigrateController.php(31): Omeka\Db\Migration\Manager->upgrade()
#5 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\MigrateController->indexAction()
#6 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#14 {main}
```

**Comment by mebrett** [comment] 2019-05-22 17:30
Note that this is all I can see when on the branch - I can't get to /admin at the moment. It just prompts the update, and then I get the error.

**Comment by jimsafley** [comment] 2019-05-22 18:59
The server you're using is likely on MySQL 5.5. The feature we're using (full-text for InnoDB) wasn't introduced until 5.6. In the next release we're going to up the required MySQL version from 5.5 to 5.6.

**Comment by mebrett** [comment] 2019-05-22 19:57
Running the IndexFulltextSearch job, ran into the error:

```
2019-05-22T19:55:23+00:00 ERR (3): Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Omeka\Entity\Media#item' that was not configured to cascade persist operations for entity: Omeka\Entity\Item@00000000587a212e0000000066a511c8. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Omeka\Entity\Item#__toString()' to get a clue. in /var/www/html/mebrett/testomekas/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 /var/www/html/mebrett/testomekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(852): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Omeka\Entity\Item))
#1 /var/www/html/mebrett/testomekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(740): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Omeka\Entity\Item))
#2 /var/www/html/mebrett/testomekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(802): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Omeka\Entity\Media))
#3 /var/www/html/mebrett/testomekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(340): Doctrine\ORM\UnitOfWork->computeChangeSets()
#4 /var/www/html/mebrett/testomekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /var/www/html/mebrett/testomekas/application/src/Api/Adapter/AbstractEntityAdapter.php(406): Doctrine\ORM\EntityManager->flush()
#6 /var/www/html/mebrett/testomekas/application/src/Api/Manager.php(236): Omeka\Api\Adapter\AbstractEntityAdapter->batchUpdate(Object(Omeka\Api\Request))
#7 /var/www/html/mebrett/testomekas/application/src/Api/Manager.php(146): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#8 /var/www/html/mebrett/testomekas/application/src/Job/IndexFulltextSearch.php(22): Omeka\Api\Manager->batchUpdate('items', Array, Array)
#9 /var/www/html/mebrett/testomekas/application/src/Job/DispatchStrategy/Synchronous.php(34): Omeka\Job\IndexFulltextSearch->perform()
#10 /var/www/html/mebrett/testomekas/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#11 /var/www/html/mebrett/testomekas/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#12 {main}
```

**Comment by jimsafley** [comment] 2019-06-04 00:12
@mebrett Try the job again. I made some changes that should fix it.

**Comment by mebrett** [comment] 2019-06-04 15:15
Full text search only works on properties which are public. If a property is marked as private, then it does not show up in full text search (admin or public side). Ex. the description [of this item set](http://dev.omeka.org/mebrett/testomekas/s/austen/item-set/9633) is private, and includes the word "herself" - if you search fulltext in the item sets for "herself" you get no results. Is this an expected behavior?

**Comment by mebrett** [comment] 2019-06-04 15:17
Also, the view of the general search "browse all pages" needs some styling. 
Clicking "View all results"
![Screen Shot 2019-06-04 at 11 16 40 AM](https://user-images.githubusercontent.com/2314070/58891308-47e8f800-86ba-11e9-9b9d-fda6b8bb6c1d.png)

Gives me this:
![Screen Shot 2019-06-04 at 11 16 47 AM](https://user-images.githubusercontent.com/2314070/58891319-4c151580-86ba-11e9-9365-8be111b38322.png)

**Comment by jimsafley** [comment] 2019-06-04 21:14
@mebrett Yes, full text search only works on properties which are public. This is by design. We're taking a safe approach to the visibility of search results, otherwise we could quite easily expose private data.

**Comment by mebrett** [comment] 2019-06-05 18:04
Another bug with the public simple search results: if an item is [Untitled] then nothing shows up in the list of search results, just a bullet point and a blank space. Once you click through to browse all items, it shows up with `[Untitled]` but not on the initial search results page:

<img width="326" alt="Screen Shot 2019-06-05 at 2 02 27 PM" src="https://user-images.githubusercontent.com/2314070/58978889-d2088d80-879a-11e9-81f4-693a3e30482c.png">

**Comment by jimsafley** [comment] 2019-06-05 19:50
f02c1f4dcbb3842f6da5056241d718d2b6e206cb fixes the [Untitled] bug.

**Comment by mebrett** [comment] 2019-06-10 20:17
It does, thank you. Things now show up as [Untitled]. 

(Just making a note to myself that search results display the item's Title property, and not whatever is set as primary for the browse. Must include this in the documentation because someone will comment)

**Closed** 2019-07-15 19:29 UTC
