### ISSUE TITLE
In Pages, blocks resist dragging and dropping and therefore reordering

### ISSUE THREAD

**Issue by hajoki** [omeka/omeka-s#1049] opened 2017-09-06 15:48 UTC

**Comment by zerocrates** [comment] 2017-09-06 22:53
Can you explain in more detail what's happening?

**Comment by hajoki** [comment] 2017-09-07 08:39
Yes sorry, for example I build this page with its blocks but let us say I want to try to put the HTML block before the Media block, then I cannot drag and drop one of the block after the other, I have to suppress and add all the blocks again. 
The mouse does become a dragging hand, so it seems that dragging and dropping should be possible here but I don't know why, the block is not dragged. Note that if I want to reorder the attachments of a Media block, this time I can drag and drop them without problem.

![screenshot from 2017-09-07 11 27 46](https://user-images.githubusercontent.com/8191742/30153656-fe505024-93bf-11e7-99a3-ca429d74071c.png)

**Comment by jimsafley** [comment] 2017-09-07 16:57
I can't reproduce the problem. Do a hard refresh and try again (Ctrl+r). Sometimes the browser doesn't load the updated scripts. Is your browser's debug console showing any errors?

**Comment by hajoki** [comment] 2017-09-08 12:33
Thank you, both before and after hard refresh I got the message:
`Loading failed for the <script> with source “/application/asset/vendor/ckeditor/skins/flat/skin.js?t=H0CF”.`
And looking at my installation, there is indeed no folder flat/ in /application/asset/vendor/ckeditor/skins

**Comment by jimsafley** [comment] 2017-09-11 13:54
CKEditor does not ship with the "flat" theme so I'm not sure why it's configured to use it. If that's causing a JS error then all subsequent scripts aren't run, so it's likely why drag and drop doesn't work.

**Comment by jimsafley** [comment] 2017-09-11 14:57
Open application/asset/ckeditor_config.js. Is there a line that sets `config.skin = 'flat';`? If so it's an outdated file and needs to be updated with the current version. To test just comment out that line and hard refresh the page. It may fix this issue and #1050.

**Comment by hajoki** [comment] 2017-09-11 15:19
Thanks, yes there was such a line and it solved the issue [#1050](https://github.com/omeka/omeka-s/issues/1050) but not the dragging and dropping, interesting. Now I don't have anything in the console, but still no possible drag and drop. Probably passing to beta 5 will solve the problem.

**Comment by zerocrates** [comment] 2018-02-23 22:20
@hajoki did you ever check if this problem was solved by an update? I believe it should have been.

**Comment by zerocrates** [comment] 2018-03-16 17:16
I'm going to close this; it can be reopened or refiled if it's still an issue.

**Closed by zerocrates** 2018-03-16 17:16 UTC
