### ISSUE TITLE
Testing available option counts within selection sidebar 

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1694] opened 2021-03-10 19:51 UTC
Test with the `resource-selector-filtered-count-fixes` branch.

This fix addresses the issue described in https://github.com/omeka/omeka-s/issues/1678, where within a resource selector sidebar, selecting all the options within a filtered view disables the resource selector even when other options are available unfiltered.

Views that include this sidebar include:

* Items > Edit
  * Item sets section
  * Sites section
* Sites > User permissions

**Comment by georgiawebgurl** [comment] 2021-03-10 21:22
Thanks! I am taking a look.

**Comment by georgiawebgurl** [comment] 2021-04-03 22:31
Issue in #1678 appears to be corrected but behavior differs between Item Sets and Sites.
- Tested Items>Edit>Item Sets: Filter/search works as expected. For item sets, when all sets have been added, the filter closes and displays All item sets have been added. As long as an item sets remain, the filter/search remains. 

One set remains unassigned:
![image](https://user-images.githubusercontent.com/14911873/113493123-b52e6580-94aa-11eb-805d-143b25fc5e70.png)


All sets assigned:
![image](https://user-images.githubusercontent.com/14911873/113493100-8c0dd500-94aa-11eb-8324-d92f7527006d.png)


- Tested Items>Edit>Sites: For sites, when all sites have been added, the filter remains but no sites are listed with an indication of sites (0). Should it close the filter/search if there are no sites left to add as it does for the Item Sets?
![image](https://user-images.githubusercontent.com/14911873/113493076-684a8f00-94aa-11eb-9fb5-0d2039816e2b.png)

**Comment by georgiawebgurl** [comment] 2021-04-03 22:49
Issue in #1678 appears to be corrected but behavior differs between Item Sets and Sites.
- Tested Items>Edit>Item Sets: Filter/search works as expected. For item sets, when all sets have been added, the search/filter closes and displays 'All item sets have been added'. As long as an item set remains, the filter/search remains. 

**One set remains unassigned for the Item:** Image 1
![image](https://user-images.githubusercontent.com/14911873/113493123-b52e6580-94aa-11eb-805d-143b25fc5e70.png)


**All sets assigned to the Item:** Image 2
![image](https://user-images.githubusercontent.com/14911873/113493100-8c0dd500-94aa-11eb-8324-d92f7527006d.png)

Removing an assigned set from an item, will restore the filter/search panel for the item. 

- Tested Items>Edit>Sites: For sites, when all sites have been added, the filter remains but no sites are listed with an indication of sites (0). Should it close the filter/search if there are no sites left to add as it does for the Item Sets (see Image 2)?

**All Sites assigned to the item**  Image 3
![image](https://user-images.githubusercontent.com/14911873/113493076-684a8f00-94aa-11eb-9fb5-0d2039816e2b.png)
 
- Tested Sites>User Permissions: For User permissions, When all users have been added to a site, the search/filter closes and displays 'All users have been added'. As long as a user remains, the filter/search remains. Removing an assigned user to a site (when all users are assigned to a search), will restore the filter/search panel.

**Comment by kimisgold** [comment] 2021-04-05 18:03
I think some of my js logic was not specific enough to account for when there are two resource selector sidebars in the same form. When troubleshooting, I saw the total available resource counts use values from the wrong tab. For instance, when the sites tab it would at some point use the total count of available item sets instead of sites. The fix in the above commit should address that.

**Comment by georgiawebgurl** [comment] 2021-04-05 19:46
Thanks! This appears to be fixed.

Tested Items>Edit>Sites: Works as expected. When all sites have been added, search/filter closes and displays 'All sites have been added'. As long as a site remains not added, the filter/search remains. Removing an assigned site (when all sites were previously  assigned to a search), will restore the filter/search panel.

**Comment by georgiawebgurl** [comment] 2021-05-18 22:40
@kimisgold Is anything else needed here? Should I put this on my documentation list?

**Comment by sharonmleon** [comment] 2021-05-19 01:49
I don’t think that there is anything to document here, since it is a fix that updates things to the expected behavior.

**Comment by georgiawebgurl** [comment] 2021-05-19 11:01
Ok, sounds good. I didn't have this on my list for documentation, so that's
likely why. :-D
Thanks!

**Comment by georgiawebgurl** [comment] 2021-05-20 18:29
@kimisgold Can this be closed?

**Closed** 2021-05-20 18:56 UTC
