### ISSUE TITLE
Reduce clicks/redundancy in attachment process

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#454] opened 2015-11-09 17:54 UTC
There seem to be several places where we can reduce the number of steps involved in the attachment process and possibly reduce confusion:

* Adding an attachment adds a blank attachment row which you need to click the wrench icon on: can we just directly open the "edit attachment" sidebar instead and then create a filled-in row when that's submitted?
* Selecting an item brings up the item info panel with the list of media and so forth, but then you have to click Select on that screen to actually choose it and then get the _real_ list of media you can select from on the attachment options screen: can we skip the initial "info" screen?

**Comment by zerocrates** [comment] 2015-11-09 18:22
Actually on attachment creation we could theoretically even go directly to the Select Item stage rather than the attachment options

**Comment by sheilabrennan** [comment] 2015-12-09 16:07
When adding an item list and adding an attachment, I'm confused by the top button (in the Attachment right side bar) that says "Select Item" but then closes the Attachment sidebar and doesn't add the item. It appears as if the only way to attach, the Apply Changes button at the bottom of hte sidebar. Is that how it works now or is that a bug? I find that top Select Item button deceiving if it isn't helping me to add the item.

**Comment by kimisgold** [comment] 2015-12-09 16:20
Here's the item attachment process logic:

* The user clicks the "add attachment" button on the admin site block. The sidebar opens to the "Select item" interface.

<img width="297" alt="screen shot 2015-12-09 at 11 08 58 am" src="https://cloud.githubusercontent.com/assets/606764/11690580/581872f0-9e65-11e5-953f-3ce95dca0319.png">

* The user clicks on one of the item titles in the "Select item" list, which then closes to reveal the item attachment sidebar.

<img width="296" alt="screen shot 2015-12-09 at 11 10 41 am" src="https://cloud.githubusercontent.com/assets/606764/11690606/8890c28e-9e65-11e5-824c-b335d7e11245.png">

* At this point, the user may select an alternative media file to represent the item or add a caption. If the user misclicked on the wrong item, they may hit the "select item" button to change the item.

* When the user is satisfied with the attachment, they click "Apply changes". The item will not attach to the site block until changes are applied.

* When the user clicks on the configure button (<img width="16" alt="screen shot 2015-12-09 at 11 14 17 am" src="https://cloud.githubusercontent.com/assets/606764/11690734/0e3fcbb4-9e66-11e5-9bde-aa7a1f277f13.png" style="display: inline-block">) of existing attachments, the sidebar will only go to the attachment options sidebar, not the "select item" sidebar. The "Select Item" button exists for users to reselect items.

So I'm wondering if it's more the labeling of the "select item" button. Would it be less confusing if it said "change item selection" or "reselect item"?

**Comment by sheilabrennan** [comment] 2015-12-09 16:35
Yes, I think it's a combo of the labeling of the "Select Item" as a button of action in the Attachment bar, and that when you click on Select Item in the Attachment bar, the item goes away. It doesn't select.

**Comment by sheilabrennan** [comment] 2015-12-09 16:36
Because if I don't make any changes, I just want to select that item and it only has one media file associated with it, I'm ready to select it. I don't know that I need to Apply Changes if I haven't changed anything.

**Comment by zerocrates** [comment] 2015-12-09 17:19
If Select Item is closing the sidebar, that's a bug.

**Comment by sheilabrennan** [comment] 2015-12-09 17:27
Bug it is: Select Item is closing the sidebar.

**Comment by kimisgold** [comment] 2015-12-09 18:38
We've determined it's not a bug, but rather a UX issue regarding the distinction between "Select Item" and "Apply Changes". This will be addressed in #485.

**Closed by kimisgold** 2015-12-09 18:38 UTC
Labels: improvement
